In [1]:
import numpy as np
import math


In [2]:
def get_T__i(theta__i, d__i, a__i, alpha__i) -> np.matrix:
    t1 = math.cos(theta__i)
    t2 = math.sin(theta__i)
    t3 = math.cos(alpha__i)
    t4 = math.sin(alpha__i)
    return np.mat([[t1,-t2 * t3,t2 * t4,t1 * a__i],[t2,t1 * t3,-t1 * t4,t2 * a__i],[0,t4,t3,d__i],[0,0,0,1]])
        

In [3]:
get_T__i(0,0,0,0)

matrix([[ 1., -0.,  0.,  0.],
        [ 0.,  1., -0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]])

In [4]:
def get_T__i_0(i, theta_all, d_all, a_all, alpha_all) -> np.matrix:
    assert i<=7, i>0
    T = np.mat(np.eye(4))
    while i>0:
        T=T*get_T__i(theta_all[i-1], d_all[i-1], a_all[i-1], alpha_all[i-1])
        i=i-1
    return T

In [5]:
theta_all=[0,0,4,0,0,0,0]
d_all=[0,2,0,0,0,0,0]
a_all=[0,0,0,0,0,0,0]
alpha_all=[0,0,0,0,0,0,0]

In [6]:
test=get_T__i_0(2,theta_all,d_all, a_all, alpha_all)
print(test)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]]


In [7]:
theta_all[1]

0

In [8]:
test[0:3,3]

matrix([[0.],
        [0.],
        [2.]])

In [9]:
W1 = W2 = np.mat(np.zeros((6,7)))

In [10]:
W2


matrix([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
[i for i in range(1,8)]

[1, 2, 3, 4, 5, 6, 7]

In [12]:
testarray=np.array([1,2,3,4,5])
testlist=[1,2,3,4,5]

In [13]:
testarray[1]

2

In [14]:
testlist[1]

2

In [15]:
np.mat(testlist)

matrix([[1, 2, 3, 4, 5]])

In [17]:
np.random.default_rng().normal(0, 0.01, (6,))

array([-0.00021489, -0.01202447, -0.0107028 ,  0.00891454,  0.00897219,
        0.01109281])